### ISSUE TITLE
Sandstone: CoR with image sharpness fails if user changes choice of slice

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CIL-Demos#140]
In the sandstone notebook the user is encouraged to try out different slice numbers
However, if they do this, the CoR later fails.

Slice selection is in cell [10]:
`filename = "slice_0270_data.mat"  # Slice numbers to choose from: 0270, 0540, 0810, 1080`

Failure occurs in cell [37]:
'data5 = CentreOfRotationCorrector.image_sharpness(backend='astra', search_range=100, tolerance=0.1)(data4)'

We need to check all of these slice numbers and only keep the suggestions for ones that we know we can run with the ImageSharpness method

**Comment by hrobarts** [comment]
![Image](https://github.com/user-attachments/assets/3a5334d3-fa34-46fe-8e33-cd300693383b)
For 0270 CofR.image_sharpness finds Rotation axis position: [44.48700389,  0.        ] but it fails for all the other slices
If I manually apply the same rotation axis position to 0540, the offset artefacts go away so we can assume the centre of rotation should be the same.


If I turn on the CofR.image_sharpness debug. 
For 0270 there is a small minimum
![Image](https://github.com/user-attachments/assets/acafa5e1-5c0e-44fb-960a-8b958ba5d5d8)
![Image](https://github.com/user-attachments/assets/11c03630-898f-4fb6-a72c-c95d03727d27)

With the same settings on 0540, there is also a small minimum in the same position. But it's less than the value away for a very negative rotation offset so it isn't selected by the algorithm.
![Image](https://github.com/user-attachments/assets/83e6c464-2fc8-432b-a671-9f303e51cd88)

Tried reducing the data binning in the first search but the algorithm still wants to select a very negative rotation offset. I don't think there's a combination of parameters that will work because increasing the search range increases it in both positive and negative directions.
![Image](https://github.com/user-attachments/assets/f03b9f6e-8d48-4b11-bf54-463c2598c597)

I'm not sure what is the cause of the 'background' in the debug plot, the y axis is
```
ag_shift = data.geometry.copy()
ag_shift.config.system.rotation_axis.position = [offset, 0]

reco = self.FBP(ig, ag_shift)(data)
return (reco*reco).sum()
```

I also tried x_correlation for 0540 and it found 
Rotation axis position: [0.08, 0.  ]
which isn't correct either.

**Comment by hrobarts** [comment]
PR #195 solves the problem by removing the suggestion to look at different slices but I suggest keeping this issue open to keep investigating with the CoR fails.

**Comment by hrobarts** [comment]
This is expected behaviour, image sharpness isn't always expected to work on parallel beam data. It was used because xcorrelation fails in this case. The update #195 closes this issue.
